import React from 'react'
import Banner from './components/Banner'
import Navbar from './components/Navbar'

const App = () => {
  return (
    <div>
      <Navbar/>
      <Banner />
      Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ut aperiam dignissimos quibusdam et atque saepe debitis velit nihil, id, expedita minus alias! Consequatur consequuntur quod incidunt soluta! Cumque doloremque beatae libero aliquam ratione, at culpa doloribus impedit? Corrupti vel reiciendis repudiandae dolore fugiat quasi doloribus esse non. Minus odit illo unde quas quibusdam molestias totam qui modi dignissimos quia, amet tempora, repudiandae, similique exercitationem maxime tenetur magni laudantium obcaecati sint. Nesciunt ullam officia dolorum suscipit vel molestiae adipisci consectetur in, alias sint porro modi nihil voluptas praesentium necessitatibus enim laborum numquam incidunt! Velit facilis ipsa, a quidem ipsam nostrum et sed eveniet vitae maxime adipisci aliquam dolorem iusto nemo earum impedit dolorum! Sit fugit voluptas dolores itaque enim mollitia alias dignissimos, corrupti odit unde eum vero rerum cumque. Eum repudiandae minima ad culpa laudantium. Itaque asperiores adipisci cupiditate officia ea necessitatibus, dicta architecto, accusamus nesciunt id placeat consequatur aliquam rem, possimus pariatur? Quibusdam, illum ducimus? Amet odio laboriosam pariatur ex nihil ut vitae quo optio laudantium accusantium minima ullam sit animi doloremque doloribus omnis laborum, sapiente veritatis dolores a quasi officiis, in aut. Sint sunt officiis qui id ullam illo magni vel quia, ex officia! Distinctio, incidunt tenetur. Quas, maxime quis. Repellat itaque optio sed. Autem assumenda dolores debitis ratione at ad aspernatur obcaecati quasi voluptas quibusdam tenetur, quia ullam consequatur id velit, blanditiis vitae ut repellat earum molestiae? Modi ducimus quidem saepe, ipsa voluptate, harum unde earum facere voluptatibus sint similique, praesentium dignissimos! Veniam, distinctio odio! Voluptatum dolorem quia, in, quo tempora animi unde nesciunt neque fugiat reiciendis, ad natus veritatis velit omnis eius praesentium sequi! Tenetur, eius in. Maxime repudiandae id ad deserunt quod quae maiores eum tempora suscipit dolorem cum architecto nemo illum nisi fuga libero, voluptatibus qui, aut aspernatur perferendis! Veritatis dolores ullam debitis quae doloremque.
      Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veritatis fugit quos suscipit sit impedit inventore obcaecati itaque nemo maiores in repellendus cum, omnis quod animi labore facere expedita architecto quidem iste similique sed tempore molestias doloribus ducimus. Sint quos ad placeat minima exercitationem eveniet, distinctio, rem praesentium asperiores error laborum doloribus minus. Officiis illo aut perferendis reprehenderit dolorem repellendus ipsam voluptatibus quibusdam aliquid dolore. Sapiente alias adipisci earum sit unde nemo ducimus temporibus laboriosam consectetur harum veritatis ipsam, mollitia sed corporis aspernatur fuga sunt. Perferendis consequatur error odit praesentium, fugiat eaque laudantium, et ad inventore voluptatum iusto, quos aliquam deleniti blanditiis natus velit sequi alias. Adipisci laborum deleniti dolores sequi aliquam veritatis repellendus doloremque quasi saepe unde sapiente placeat repudiandae numquam accusantium vero delectus repellat fugit inventore, aliquid voluptate distinctio, quod ab reprehenderit? Quasi mollitia assumenda reprehenderit repellat. Qui magni molestias minima dignissimos deleniti velit temporibus veritatis, ipsa ipsum repellat ab dolore maxime. Nam, ipsum corrupti, tenetur cumque quibusdam odio debitis a laboriosam dolores dicta consequatur voluptate commodi quidem dolore ut consectetur voluptates delectus adipisci doloremque sed. Explicabo pariatur iste vero, aspernatur, quos nostrum quaerat minima expedita, consectetur dolore officiis! Voluptatem distinctio sit, doloribus enim, corporis ut possimus fugit praesentium impedit delectus voluptas a tempora odio minus eos quia vitae velit ullam nobis veritatis hic necessitatibus. Tempore praesentium vel commodi provident saepe illum perferendis consectetur accusamus porro repellendus! Consectetur, nobis? Incidunt itaque, assumenda perferendis, sit nesciunt illum libero amet, soluta nostrum tempora voluptatum? Ipsam, facilis quidem id illum nihil maiores tempore porro aliquam repudiandae cupiditate quisquam dolores quo, quam deserunt, impedit harum obcaecati. Rerum, tempore vero. Suscipit quas facere ipsam rem nesciunt veritatis. Eligendi commodi obcaecati aperiam porro id qui officia nostrum sunt harum neque ea enim nobis dolor, eius distinctio. Voluptatem totam repudiandae exercitationem quod dolores, dignissimos veritatis id.
    </div>
  )
}

export default App